# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
language: node_js
node_js:
  - 13

services: docker

install:
  - echo "nothing to instal"

before_script:
  - echo "no tests"
# Build
script:
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tagging
  - docker tag udagram-api-feed kokose/udagram-api-feed:v1
  - docker tag udagram-api-user kokose/udagram-api-user:v1
  - docker tag udagram-api-feed kokose/udagram-frontend:latest
  - docker tag udagram-api-feed kokose/udagram-reverseproxy:latest

after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kokose/udagram-api-feed:v1
  - docker push kokose/udagram-api-user:v1
  - docker push kokose/udagram-frontend:latest
  - docker push kokose/udagram-reverseproxy:latest
