apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  AWS_ACCESS_KEY_ID: ASIAZ2WUWGXWR5FKNQFL
  AWS_SECRET_ACCESS_KEY: NAUIgLFZfOp2xJ7WtmuoVqhkq/z8i60n+hBXydmk
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEPL//////////wEaDIrFxa12hZyZDlAkHSLVAfXmhVWNUyEkgPvaKnhFlxTJZd9jlu+xBY3SfrOJnVwundghWjKzJ39Oy3nyl0jAy4SsV5TeQOMFLw8yCLNp6+RHWxMgP5WTfJalg/nXu3cSENh2OHpwMlIVQi4rtnrIRv4mYXrZiVeT11e+EBO+qGFm3cPYok5frJfEpHl7jH/v1W/T0VbLxCwsZMMkZ74Pqf8AYPyIib/X+qxKCNI5E+i2esvI1SCn6FONkUcfgr5E+jiHQXMHe/zUYZsZyPGVvONVom6KkrpbcOitq5PhwFmq1y5DcSjZ9aCaBjItW8Z2O2OjOtv9+9l6xT8OoWWFj7quNXnX9Abd7VHsA+Qffl9/0bGUoW/PNA30
