apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy

    spec:
      containers:
        - name: udagram-reverseproxy
          image: docker.io/kokose/udagram-reverseproxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "128Mi"
              cpu: "1024m"
            limits:
              memory: "2048Mi"
              cpu: "2048m"

          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret

          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-secret
              readOnly: true

      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
            optional: false
