apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy

    spec:
      containers:
        - name: udagram-reverseproxy
          image: docker.io/kokose/udagram-reverseproxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-secret
              readOnly: true

      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
            optional: false
