apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 80
  selector:
    service: udagram-reverseproxy
